# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 笔记（万篇）
    url: 'books-gallery'
    identifier: books-gallery
    weight: 10
  - name: 知识图谱
    url: "#knowledge-map"
    weight: 20
  - name: 实验室
    identifier: lab
    url: "#"
    weight: 30
  - name: Craft 方块世界
    parent: lab
    url: "/galaxy-home/gh-craft"
    weight: 31
  - name: 3D 知识卡牌
    parent: lab
    url: "/galaxy-home/glossary-cards"
    weight: 32
  - name: 其他阅读渠道
    identifier: blog
    weight: 70
  - name: 知乎
    parent: blog
    pre: <img style="width:16px;height:16px;display:inline-block;margin-right:8px" src="https://ngte-superbed.oss-cn-beijing.aliyuncs.com/item/20230218234451.png"></img>
    url: https://zhuanlan.zhihu.com/wxyyxc1992
    weight: 71
  - name: SegmentFault
    parent: blog
    pre: <img style="width:16px;height:16px;display:inline-block;margin-right:8px" src="https://ngte-superbed.oss-cn-beijing.aliyuncs.com/item/20230219113556.png"></img>
    url: https://segmentfault.com/blog/wxyyxc1992
    weight: 72
  - name: 掘金
    parent: blog
    pre: <img style="width:16px;height:16px;display:inline-block;margin-right:8px" src="https://ngte-superbed.oss-cn-beijing.aliyuncs.com/item/20230219113519.png"></img>
    url: https://zhuanlan.zhihu.com/wxyyxc1992
    weight: 73
