# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: my_theme
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '王下邀月熊'
    description: 'Next-gen Tech Edu'
    twitter: 'wx-chevalier'
  analytics:
    google_analytics: 'G-40NYXJ8823'
    baidu_tongji: '56df1177bce405601b0ecdd7208f75c6'
  verification:
    google: 'google69a5cccb61297807'
    baidu: 'cqmZHEleVh'

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    show_github: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© 2017-2022 NGTE all rights reserved'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '下午 3:04'

# Publication

publications:
  date_format: '2006-01-02'

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/wx-chevalier'
    content_dir: content
    branch: master
  comment:
    provider: 'disqus'
    disqus:
      shortname: 'ngte'
      show_count: true
    # commento:
      # url: 'wx-chevalier'
  search:
    provider: algolia
    algolia:
      app_id: 'WINJ66Z2PG'
      api_key: '5869efb5b321479228f1cd41370584b3'
      index_name: 'ngte-website'
      show_logo: true
reading_time: true
section_pager: true
subscribe:
  enable: true
